//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FinalProject.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FINALPROJECT_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDD_SEARCH_DIALOG               130
#define IDD_GRAPH_DIALOG                131
#define IDC_BUTTON1                     1000
#define btnSaveEdit_SH                  1000
#define btnSearchProceed_SH             1000
#define comboDataType                   1001
#define btnAddPerson                    1003
#define btnClearAll                     1004
#define btnSearch                       1005
#define btnCreateGraphs                 1006
#define txtID                           1007
#define txtFullName                     1008
#define btnSaveDetails                  1009
#define txtAddress                      1010
#define comboGender                     1011
#define comboStatus                     1012
#define dtpBirthDate                    1013
#define btnAbout                        1014
#define comboCity                       1015
#define txtInfectorID                   1016
#define comboInfectionAreaType          1017
#define dtpHospitalEntry                1018
#define comboHospital                   1019
#define comboSicknessLevel              1020
#define comboVentilated                 1021
#define dtpRecoveryDate                 1022
#define dtpPositiveTest                 1023
#define txtIsolationAddress             1024
#define comboIsolationCity              1025
#define staType                         1026
#define staHeader1                      1027
#define staHeader2                      1028
#define staID                           1029
#define staName                         1030
#define staGender                       1031
#define staBirthdate                    1032
#define staCity                         1033
#define staAddress                      1034
#define staStatus                       1035
#define staPosTest                      1036
#define staIDInfector                   1037
#define staWarningInfector              1038
#define staAreaType                     1039
#define staRecoveryDate                 1040
#define staIsolatedCity                 1041
#define staIsolatedAddress              1042
#define staHospitalName                 1043
#define staSicknessLevel                1044
#define staVentilated                   1045
#define staHospitalDate                 1046
#define btnCreate                       1047
#define staHeader3                      1048
#define btnSaveAll                      1049
#define IDC_RADIO1                      1060
#define dtpIsolationEntry               1060
#define btnDelete_SH                    1062
#define btnSearchID_SH                  1063
#define txtSearchID_SH                  1064
#define txtID_SH                        1065
#define txtFullName_SH                  1066
#define comboGender_SH                  1067
#define comboCity_SH                    1068
#define dtpBirthdate_SH                 1069
#define comboStatus_SH                  1070
#define txtInfectorID_SH                1071
#define comboInfectionArea_SH           1072
#define dtpPositiveTest_SH              1073
#define dtpRecoveryDate_SH              1074
#define comboIsolationCity_SH           1075
#define comboIsolationAddress_SH        1076
#define comboHospitalName_SH            1077
#define comboSicknessLevel_SH           1078
#define comboVentilated_SH              1079
#define dtpHospitalDate_SH              1080
#define txtAddress_SH                   1081
#define comboDataType_SH                1082
#define comboSearchOpt                  1082
#define staSearchID_SH                  1083
#define staID_SH                        1084
#define staFullName_SH                  1085
#define staGender_SH                    1086
#define staCity_SH                      1087
#define staAddress_SH                   1088
#define staBirthdate_SH                 1089
#define staStatus_SH                    1090
#define staDataType_SH                  1091
#define staInfectorID_SH                1092
#define staDataType_SH2                 1092
#define staInfectionArea_SH             1093
#define staPositiveTest_SH              1094
#define staRecoveryDate_SH              1095
#define staIsolationCity_SH             1096
#define staIsolationAddress_SH          1097
#define staHospitalName_SH              1098
#define staSicknessLevel_SH             1099
#define staVentilated_SH                1100
#define staHospitalDate_SH              1101
#define staError_SH                     1102
#define IDC_COMBO1                      1103
#define txtExposedID                    1105
#define staExpoedID                     1108
#define staIsolationEntry               1109
#define staExposedID                    1110
#define staAddPerson                    1111
#define comboSearchStat                 1112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
